### ISSUE TITLE
Add support for secured access to published (production) content

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/cloud-sdk-swift#17]
Delivery API now supports authenticated access. Content is secured using an API key. The developer is able to turn the authenticated access on and off for the whole project. 

Information about secured API:
* https://kenticocloud.com/blog/secure-access-for-delivery-api
* https://developer.kenticocloud.com/docs/securing-public-access

See sample implementation on .net SDK:
* https://github.com/Kentico/delivery-sdk-net/pull/96

Hint:
- The authenticated access works similarly to the Preview API with the difference that the endpoint remains the same. So only an authentication header is being added.

**Comment by makma** [comment]
Afaik this is how preview API already works - imo it means the user could use his secret token instead of preview api key and the content will be returned according to key (preview vs secured vs public if no key is sent). If I understand it correctly - the only required task it to change documentation comments and add tests. Am I right?

**Comment by petrsvihlik** [comment]
The preview API uses a different endpoint...we need to support both scenarios. But yeah, it'll be very similar.

**Comment by makma** [comment]
Yes, you are right, thank you for the clarification!

**Comment by petrsvihlik** [comment]
closed in #42
